
# devtool: bashrc
# Include ~/.bashrc.d/ when using login shell
if [ -d ~/.bashrc.d ]; then
	for script in ~/.bashrc.d/*.sh; do
		[ -r "$script" ] && . "$script"
	done

	for script in ~/.bashrc.d/devtool/*.sh; do
		[ -r "$script" ] && . "$script"
	done
	unset script
fi

# Switch to fish for interactive
# Note: REMOTE_CONTAINERS_IPC is set during Dev Containers userEnvProbe (undocumented)
if [[ ! -v REMOTE_CONTAINERS_IPC ]] && [[ -z "$NO_FISH" ]] && command -v fish &> /dev/null; then
	exec fish --login
fi
