[tools]
"aqua:bats-core/bats-core" = "latest"
"cargo:cargo-sweep" = "latest"
"cargo:topgrade" = "latest"
awscli = { version = "latest", symlink_bins = "true" }
chezmoi = "latest"
dprint = "latest"
dua = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
gitleaks = "latest"
lefthook = "latest"
node = "24"
ripgrep = "latest"
rust = "latest"
shellcheck = "latest"
starship = "latest"
tmux = "3.6a"
usage = "latest"
